"use strict";
var z1 = 1;
var z2 = 2;
var z3 = "1";
document.write((z1 > z2) + "<br />");
document.write((z1 < z2) + "<br />");
document.write((z1 >= z2) + "<br />");
document.write((z1 <= z2) + "<br />");
document.write((z1 == z2) + "<br />");
document.write((z1 != z2) + "<br />");
document.write((z1 == z3) + "<br />");
document.write((z1 === z3) + "<br />");
document.write((z1 !== z3) + "<br />");
document.write((1 == true) + "<br />");
document.write((0 == true) + "<br />");
document.write((42 == true) + "<br />");